### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by ryaholm** [CSDTs/django_git_tinymce#104]
I thought the gold key could be a good logo for OPENS. No one likes it, however, and are confused by it (why are there all these keys everywhere?). Other logos I thought of for OPENS: a lighthouse... etc.

Need to replace favicon with a new logo, and also update the default repo logo too. The CSDT favicon from https://github.com/RPI-HASS/rpi_csdt_community might suffice.

**Comment by duffym4** [comment]
Would the CSDT logo split onto two lines work as the favicon?

Rough mock-up:
![image](https://user-images.githubusercontent.com/36003776/36872216-80bb4a8c-1d72-11e8-89f7-3ab0175a1160.png)

**Comment by SillyInventor** [comment]
The CSDT favicon & Logo as designed by Dr. Bennet, are as available on the CSDT page. OPENS doesn't get its own logo.

**Comment by ryaholm** [comment]
https://github.com/RPI-HASS/rpi_csdt_community/blob/master/static/favicon.ico

Here's the CSDT favicon
