### ISSUE TITLE
Use repo description

### ISSUE THREAD

**Issue by ryaholm** [CSDTs/django_git_tinymce#105]
Right now we have a textfield for repo description but that isn't expressed anywhere on the repo webpage. Maybe it should follow the Repo Name?

![screen shot 2018-02-28 at 2 34 20 pm](https://user-images.githubusercontent.com/23264375/36809020-c4602ab6-1c94-11e8-9907-98582ac7b1e0.png)

**Comment by duffym4** [comment]
I believe this is already implemented. In your example 'test_repo' is the Repo Name and 'Test_Repo' is the repo description.
![image](https://user-images.githubusercontent.com/36003776/36870883-734c541c-1d6e-11e8-9454-092dcf304df7.png)

**Comment by ryaholm** [comment]
Awesome, thanks for double checking.
