### ISSUE TITLE
Add ".." to first file in file listing if not root folder

### ISSUE THREAD

**Issue by ryaholm** [CSDTs/django_git_tinymce#111]
If you are not in root folder and down the hierarchy, there should be a ".." link above the first file listing (or possibly as the first file listing) so that users can easily pop up a directory.

Example on github:
![screen shot 2018-02-28 at 4 24 46 pm](https://user-images.githubusercontent.com/23264375/36813923-0e9eade6-1ca4-11e8-8707-97190e5b48de.png)

**Comment by ryaholm** [comment]
This is probably easiest done in React, not python backend. It would basically take the folder string and use a regex to remove the last <last_dir>/ after the second to last "/" and use that as the link to ".." hardcoded into the frontend menu.

https://stackoverflow.com/questions/16750524/remove-last-directory-in-url/16750711

**Comment by duffym4** [comment]
This is another issue I've fixed in my branch, although I did it mostly in python back-end, which might not be the best implementation?

**Comment by ryaholm** [comment]
Ah, if it works with python backend that's good too.

**Comment by ryaholm** [comment]
Quick question: If you want to remove a folder, and there isn't any ```delete``` option on the ".." file, it will be impossible to completely remove the folder, correct? I know ".." is acting as a placeholder but if the user wants to delete the folder that it is contained in they are essentially required to remove all the file in the folder, right?

**Comment by duffym4** [comment]
Yes, I mostly implemented folder deleting but there are still some bugs with it I am working on.

**Comment by ryaholm** [comment]
Great work! 🥇 👍 🐲
