### ISSUE TITLE
Commit Message details 404'ing because current subfolder is included

### ISSUE THREAD

**Issue by ryaholm** [CSDTs/django_git_tinymce#115]
Setup:
* create a new file in a subfolder
* navigate to that subfolder
* near top of menu, "Last commit message by ____: ..." and click the dot-dot-dot

Error:
* Page looks for ```<username>/<repo_name>/<current_folder>/commit/<hex_code>```
instead of ```<username>/<repo_name>/commit/<hex_code>```

Expected Behavior:
* That link should always be ```<username>/<repo_name>/commit/<hex_code>``` and not include current directory in the href.

**Comment by duffym4** [comment]
I've fixed this in my branch. I'm going to work on a merge as soon as I fix a few problems with my branch so that all the bug fixes are up to date.

**Comment by ryaholm** [comment]
Awesome, just saw this bug while poking around this morning and should have cross referenced your PR.
