### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by SillyInventor** [CSDTs/django_git_tinymce#69]
Ya'll need to fix your linting errors. The thousand or so you have should be clear evidence of why you lint as you write.... also because it helps teach you basic formatting.

**Comment by ryaholm** [comment]
I'll lint this morning and see how much I can chunk out of it.

@slinv You might want to make sure from this point on that you set your IDE to use spaces instead of tabs to avoid throwing future linting errors. It's good practice, anyway.

**Comment by ryaholm** [comment]
Alright, I just turned on linting on Travis. 🍺 🍺 🍺
