### ISSUE TITLE
Chunk of HTML Code in repos.models.py

### ISSUE THREAD

**Issue by SLiNv** [CSDTs/django_git_tinymce#83]
Since the same [HTML starter code](https://github.com/CSnap/django_git_tinymce/blob/995e0ffde061b2e54c3292b13f7405a73dbe72ae/repos/models.py#L106) is pre-loaded for all users, we can consider moving the big chunk to a utility module, i.e. repos.utils.py, to keep repos.models.py clean and for better code flexibility.

**Comment by ryaholm** [comment]
I think this is no longer an issue, since we're not generating default web pages anymore.
